title: Three's Haskell Blog
description: Learning Haskell with a focus on developing real-time trading algorithms
theme: jekyll-theme-slate

head: |
  <script type="text/javascript" async
    src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/MathJax.js?config=TeX-MML-AM_CHTML">
  </script>